name: Python App Launch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install numpy
      run: pip install numpy==1.23.0

    - name: Install other dependencies
      run: pip install -r requirements.txt

    - name: Run Python application
      run: python app.py
